# @package _global_
# Debug run preset: fast, deterministic, minimal logging
total_steps: 5000
seed: 42
deterministic: true

# Logging
log_interval: 1
save_freq: 1000
eval_freq: 1000
use_wandb: false
use_mlflow: false

# Performance (disabled for debugging)
amp: false
torch_compile: false
torch_deterministic: true

# Agent overrides for faster debugging
agent:
  n_steps: 128
  batch_size: 32
  n_epochs: 2