# Minimal, sane PPO defaults for CartPole debugging
algo_name: ppo
gamma: 0.99
gae_lambda: 0.95
learning_rate: 3.0e-4
entropy_coef: 0.0
value_coef: 0.5
clip_ratio: 0.2
num_minibatches: 4
update_epochs: 4
rollout_len: 2048
max_grad_norm: 0.5
normalize_adv: true