# Evaluation session defaults
seed: 42
deterministic: true
device: auto
episodes: 10
render: false
checkpoint: null   # path to ckpt; null prints config + exits for now

# Composition targets (select via CLI when needed)
env: cartpole
algo: ppo