# Main configuration file for evaluation
defaults:
  - env: cartpole
  - algo: ppo
  - _self_

# Evaluation session defaults
seed: 42
deterministic: true
device: auto
log_dir: null  # Auto-detect latest run from artifacts/{env}/{algo}/{seed}/ structure

# Evaluation configuration
eval:
  n_episodes: 10
  record_video: true
  video_dir: null  # Auto-resolved to artifacts directory
  load_checkpoint: latest  # "latest" or explicit path
  run_after_train: true