# @package _global_
agent:
  _target_: rrl.agents.ppo.PPOAgent
  name: "PPO"
  policy: "MlpPolicy"
  
  # PPO hyperparameters
  learning_rate: 3e-4
  n_steps: 2048
  batch_size: 64
  n_epochs: 10
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  clip_range_vf: null
  ent_coef: 0.0
  vf_coef: 0.5
  max_grad_norm: 0.5
  
  # Network architecture
  policy_kwargs:
    net_arch: [64, 64]
    activation_fn: "tanh"
    ortho_init: true